name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: if not fork
        if: ${{ !github.event.repository.fork }}
        run: echo 1

      - name: if fork is not true
        if: github.event.repository.fork != true
        run: echo 2

      - name: if repository is issueset/test-github-actions
        if: github.repository == 'issueset/test-github-actions'
        run: echo 3

      - name: if same repo
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        run: echo 4
